module.exports = {
    units: [
        {
            id: 2,
            name: 'Unit 2',
            type: 2,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 1,
            y: 1,
        },
        {
            id: 3,
            name: 'Unit 3',
            type: 2,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 2,
            y: 3,
        },
        {
            id: 4,
            name: 'Unit 4',
            type: 3,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 5,
            y: 8,
        },
        {
            id: 5,
            name: 'Unit 5',
            type: 3,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 11,
            y: 13,
        },
        {
            id: 6,
            name: 'Unit 6',
            type: 4,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 11,
            y: 3,
        },
        {
            id: 7,
            name: 'Unit 7',
            type: 4,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 8,
            y: 4,
        },
        {
            id: 8,
            name: 'Unit 8',
            type: 4,
            idUser: 2,
            pa: 20,
            view: 7,
            eff: 50,
            moral: 100,
            xp: 0,
            formation: 1,
            x: 2,
            y: 7,
        },
    ],
}
